### ISSUE TITLE
Generate the extension vsix for each build

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/vscode-granite#8]
CI build needs to :

- build extension vsix
- attach built vsix to CI runs (useful to test PRs)
- attach built vsix to rolling Development release for the main branch

**Comment by fbricon** [comment]
@lavanyaj3 any progress on this one? I can make the changes myself now if you're having some issues.

**Comment by lavanyaj3** [comment]
Hi Fred,

The code is ready with the change.
Apologises for the delay in responding. We were having public holiday in Kochi location .

Will create Pull request today

Thanks,
Lavanya

From: Fred Bricon ***@***.***>
Date: Tuesday, 17 September 2024 at 6:19 PM
To: redhat-developer/vscode-granite ***@***.***>
Cc: Lavanya J ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] Re: [redhat-developer/vscode-granite] Generate the extension vsix for each build (Issue #8)
@ lavanyaj3 any progress on this one? I can make the changes myself now if you're having some issues. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned. Message ID: <redhat-developer/vscode-granite/issues/8/2355665795@ github. com>


@lavanyaj3<https://github.com/lavanyaj3> any progress on this one? I can make the changes myself now if you're having some issues.

**Comment by fbricon** [comment]
Fixed with #35
